name: flutter_firebase_chat_core
description: >
  Actively maintained, community-driven Firebase BaaS for chat applications
  with an optional chat UI.
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^2.4.0
  firebase_auth: ^3.0.1
  flutter_chat_types:
    git:
      url: git://github.com/datasoil/flutter_chat_types
      ref: f3db584ee3efc556f76e7bd139bee5fdc5a19da6
  meta: ^1.3.0  
  firebase_storage: ^10.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1
